environment:
  nav2_map: carter_warehouse_navigation.yaml
  mapf_map: carter_warehouse_navigation_mapf.yaml

robots:
  - name: robot1
    initial_pose:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0
    goal_pose:
      x: -4.0
      y: 15.0
      z: 0.0
      yaw: 3.14159

  - name: robot2
    initial_pose:
      x: 2.5
      y: 0.0
      z: 0.0
      yaw: 3.14159
    goal_pose:
      x: -7.5
      y: -5.5
      z: 0.0
      yaw: 1.57079632679

  - name: robot3
    initial_pose:
      x: 0.0
      y: 2.5
      z: 0.0
      yaw: 1.57079632679
    goal_pose:
      x: 5.0
      y: -4.0
      z: 0.0
      yaw: 1.57079632679
